### ISSUE TITLE
JCE update site (pkg_jce.xml, for example) still uses clientid as integer, not as string (cause problems in J4)

### ISSUE THREAD

**Issue by AndNovAtor** [widgetfactory/jce#101]
**Describe the bug**
As described in https://docs.joomla.org/Potential_backward_compatibility_issues_in_Joomla_4#Updater and https://github.com/joomla/joomla-cms/pull/35822, since "old days", using ```clientid``` as integer (```1```/```0``` for administrator/site) was deprecated. Now, in Joomla 4, "only" string is used, that cause multiple problems with JCE. 

First of all, it's deprecated. But most critically, when ANY extension uses this old behavior on Joomla 4, checking for extension updates on default Nginx+PHP-FPM configuration cause Nginx http body "overload" by php stderr with error ```"Trying to get property 'id' of non-object"```, and extension update page loading FAILED with http 502 error (second reload works - extension update cache is used). On Apache-PHP it's simply logs a lot of string of related error.

Anyway, all JCE related update site xml should be updated to use clientid as string (to ```administrator```/```site```).

So, see main update site url - https://cdn.joomlacontenteditor.net/updates/xml/editor/pkg_jce.xml - still ```<client>0</client>```, should to use ```<client>administrator</client>```, as, for example, is used by OSMap extension [works both for Joomla 3.x and Joomla 4.x], see https://deploy.ostraining.com/client/update/free/stable/com_osmap [it's xml url].

**To Reproduce**
Open https://cdn.joomlacontenteditor.net/updates/xml/editor/pkg_jce.xml

~**Expected behavior**~
~```<client>administrator</client>```~

**Actual behavior**
```<client>0</client>```

**Additional context**
(Site url for JCE seems "actual", "tested" with last JCE Editor 2.9.17)

UPDATE: I was wrong, edited (only for components):
**Expected behavior**
```client>site</client>```

**Comment by ryandemmer** [comment]
Thank you, this is fixed now.

**Comment by AndNovAtor** [comment]
Sorry, but now all new version ignored by J3 and J4.... Strange
So even for J3 update proces now "broken". Sorry for that =(

**Comment by AndNovAtor** [comment]
Sorry, looks like I misprinted, maybe needed ```site``` for JCE extension, not ```administrator```

```client_Id = 1 means admin access client_Id = 0 means frontend access```

**Comment by AndNovAtor** [comment]
YES, thanks, all works now

**Comment by ryandemmer** [comment]
Ok those are updated now.

`site` is for components and packages, `administrator` is for plugins.

**Comment by AndNovAtor** [comment]
Ok, thank you for your promptness.

If You checked ALL xml-s, please close issue (as "resolved" =).
