### ISSUE TITLE
Under some circumstances modal-footer of Joomla media modal hidden by JCE's media.css

### ISSUE THREAD

**Issue by ReLater** [widgetfactory/jce#104]
I know how to fix it in my extension but wanted to report it here. Maybe a bug. Maybe not. Don't waste your time with it ;-)

**Describe the bug**
- Joomla 4.0.5
- JCE Free 2.9.18
- A custom module that loads in edit form a subform XML and gets an additional fieldset (tabulator) by a plugin via `onContentPrepareForm`. 
- Both have a custom XML file with form field definitions.

One has a field (type media):

```
<field name="foto" type="media" default=""
label="MOD_SPLIDEGHSVS_FOTO"
preview="true"/>
```

The other a field (type mediajce):

```
<field name="lederBG" type="mediajce" default=""
addfieldpath="plugins/system/jce/fields"
label="Bla bla"/>
```

- Now **disable `replace_media_manager` in JCE options**!

- The field combination above leads to the situation that `$hasMedia` is `true`
- - https://github.com/widgetfactory/jce/blob/2.9.18/plugins/system/jce/jce.php#L174-L176
- and that `media.css` is loaded
- - https://github.com/widgetfactory/jce/blob/2.9.18/plugins/system/jce/jce.php#L194

- The result is that the field with `type="media"` displays the Joomla Media Manager as expected but the Insert/Cancel buttons in `<div modal-footer>` are hidden by the CSS file `media.css` and one can't insert the image via Joomla's Media Manager.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/20780646/147395225-a527c032-c479-47ca-92b6-fc8437734b1c.png)

![grafik](https://user-images.githubusercontent.com/20780646/147395230-8464bcc1-539b-4be2-8f06-2ea5f24708d0.png)

**Comment by ryandemmer** [comment]
Fixed in commit - https://github.com/widgetfactory/jce/commit/c10cb829ad02ea8705d30798a870602b6fab75e8

Thank you.

**Comment by ReLater** [comment]
Works so far and the buttons are visible.

But:
For the form field with type="mediajce" the height of the `<div modal-body>` is too low now. 

See images please. Joomla 4.0.5 backend. Firefox.

### 1

![grafik](https://user-images.githubusercontent.com/20780646/147744118-9602c575-82c0-45c8-a81c-147963aed9c2.png)

![grafik](https://user-images.githubusercontent.com/20780646/147744147-bcb7c525-5121-4812-b297-11251d8f3cbf.png)

### 2 (changed via browser inspector)

![grafik](https://user-images.githubusercontent.com/20780646/147744331-bf839283-7bec-456d-83f7-f8b761feb1fd.png)

![grafik](https://user-images.githubusercontent.com/20780646/147744387-79ec0c79-309c-45a0-992e-fa79ac7d39a9.png)

**Comment by ryandemmer** [comment]
Fixed in https://github.com/widgetfactory/jce/commit/451403d8201f550d66d8ce4f63467f688dab8ae3 and https://github.com/widgetfactory/jce/commit/c396cc8bfae2d58e7f390f4f9475fb58d6fc0897

**Comment by ReLater** [comment]
Everything looks fine now in my test case above. Thanks!
