### ISSUE TITLE
Can't delete alone custom Style (Joomla 4)

### ISSUE THREAD

**Issue by DSist** [widgetfactory/jce#106]
**Describe the bug**
I added two custom styles and couldn't remove both.

**To Reproduce**
1. Go to 'Profiles - Default - Plugin Parameters - Style Select'
2. Add two styles at once
3. Click on "Save & New" 
4. Remove both styles
5. Click on "Save"
6. The last style always exists no matter how I try to remove it

**Expected behavior**
No styles should be shown both in the Panel and the editor itself

**Additional context**
Clean Joomla 4.0.5 installation

**Comment by ryandemmer** [comment]
When you click Save & New, you are saving the existing profile and creating a new empty one, so it will not retain any profile parameters.

**Comment by DSist** [comment]
But I can't remove the last style after that.

**Comment by DSist** [comment]
Have just tried. The last alone style always exists.

**Comment by DSist** [comment]
I click on the 'Trash can' icon and 'Save' button after that to no avail.

**Comment by ryandemmer** [comment]
Fixed in commit - https://github.com/widgetfactory/jce/commit/98da15f078c5bb0590b7500f8f2628dcd0ff92c4

**Comment by ryandemmer** [comment]
The fix will be available in the next update. Until then, delete the values you have added to the Style Format, which will effectively remove it.

**Comment by DSist** [comment]
Thank you!
