### ISSUE TITLE
Joomla 4.1 with weblinks component. Link search doesn' display weblinks.

### ISSUE THREAD

**Issue by ReLater** [widgetfactory/jce#108]
**To Reproduce**
- Joomla 4.1.1.dev. Also reported for 4.1.0 in german forum.
- Install Joomla's decoupled Weblinks Component, e.g. via webinstaller.
- Create a weblink in weblinks component.
- In JCE `profile configuration > Plugins > Link` activate `Show Weblinks Links List` for link search in editor.
- Open an article. Click link button in editor bar.
- ==> No weblinks to see in search area.

**Expected behavior**
Created weblink selectable to insert link in editor text.

**Comment by ryandemmer** [comment]
Fixed in commit - https://github.com/widgetfactory/jce/commit/7c0f538df79fb5f63546e60d3d8b00e6c20abfb6

**Comment by ReLater** [comment]
Tested successfully with Joomla 4.1.1-rc2-dev.

Thanks a lot for prompt solution!
