### ISSUE TITLE
the installation from JED failed becouse of the PHP version 7.4 is required

### ISSUE THREAD

**Issue by radeknoone** [widgetfactory/jce#109]
Hi

the installation from JED failed becouse of the PHP version 7.4 is required. I

Joomla version used:
Joomla! 3.10.8 Stable [ Daraja ] 30-March-2022 13:28 GMT

JCE version used:
Version 2.9.22 (last updated on 31 March 2022)
License GPLv2 or later
Download Type Free download
Added On 05 March 2006
Compatible Versions 3.x, 4.x

PHP version used 7.3.29.

Result:
![image](https://user-images.githubusercontent.com/23701185/162255316-c69132fa-2847-4bdc-a77d-776a566c9433.png)

As the Joomla still supports php versions 5+, there should be the compatibility hold for all available (and Compatible) versions. As I saw the code of JCE, there is not any specific function used from php 7.4. There is just unnecessarily strict test in code for 'php version LE 7.4`.

**Comment by ryandemmer** [comment]
JCE requires PHP 7.4 or later - https://www.joomlacontenteditor.net/support/documentation/editor/requirements

**Comment by radeknoone** [comment]
Hi, thank you for your reply. Would you be so kind and explain shortly what used function is not available in the older release of php (7.3.29 for example)?

In case there is tech reason to not support older release, the JCE should not support Joomla 3x versions (as Joomla supports php 5.3.10 end higher).

**Comment by radeknoone** [comment]
What is the reason for support PHP 7.4 or later? There is not technical reason - in the contrary it brakes the compatibility with Joomla and is agains the principle of longterm support enterprise distros (RHEL).

**Comment by ryandemmer** [comment]
> What is the reason for support PHP 7.4 or later?

Because I don't want to support PHP versions older than 7.4. Earlier versions are not supported by PHP - https://www.php.net/eol.php

**Comment by ryandemmer** [comment]
Supporting older versions requires testing on older versions, and many changes in PHP 7.4 and later which are now standard, are not supported in earlier versions. This would require extensive testing to try and prevent issues with older versions of PHP, and I don't have the time or the inclination to do that.

If you need to use PHP 7.3, then use JCE 2.9.20 or earlier.

**Comment by radeknoone** [comment]
Thanks for your time and explanation!
