### ISSUE TITLE
Use of undefined constant JSON_UNESCAPED_SLASHES 

### ISSUE THREAD

**Issue by dhyano** [widgetfactory/jce#11]
Hello
new to this and not sure how to post.
Using Joomla 3.6.4 with Yootheme ZOO component.
I upgraded to JCE 2.6.2 and now when I go into a ZOO item and look at the editor I see the following errror message above the editor box:

Notice: Use of undefined constant JSON_UNESCAPED_SLASHES - assumed 'JSON_UNESCAPED_SLASHES' in /home/essentiallifeconsulting.com/public_html/administrator/components/com_jce/models/editor.php on line 273

See attached pic.
Any ideas?
Thank you
Dhyano
![senza nome](https://cloud.githubusercontent.com/assets/24719272/21430735/b0c7352e-c864-11e6-94a7-b238e83c3588.jpg)

**Comment by ryandemmer** [comment]
JCE requires PHP 5.4 or later.

JSON_UNESCAPED_SLASHES is available in PHP 5.4 so I assume you are getting this error because you are using an older PHP version on your server.

**Comment by dhyano** [comment]
Yes on the PHP version on server is not 5.4.
So, should I reinstall JCE Legacy version 2.531?

Thank you
Dhyano

**Comment by ryandemmer** [comment]
> So, should I reinstall JCE Legacy version 2.531?

No, you should update your server to a newer PHP version. PHP versions below 5.6 are no longer supported by PHP - http://php.net/supported-versions.php

**Comment by dhyano** [comment]
I contacted the host and for now they do not plan to upgrade their server to PHP higher than 5.4.
So it is OK to stay with JCE 2.6 for now. does not create any problems with the site or editing?

**Comment by ryandemmer** [comment]
> I contacted the host and for now they do not plan to upgrade their server to PHP higher than 5.4.

You should look for a new host.

> So it is OK to stay with JCE 2.6 for now. does not create any problems with the site or editing?

PHP 5.4 is the absolute minimum for JCE 2.6
