### ISSUE TITLE
JCE Pro will not install on version 2.9.23.

### ISSUE THREAD

**Issue by ChristineWk** [widgetfactory/jce#112]
Describe the bug
informed by: https://forum.joomla.de/thread/16001-jce-pro-l%C3%A4sst-sich-in-version-2-9-23-nicht-installieren/

<code>
Es ist ein Fehler aufgetreten.
0 Call to undefined method Joomla\CMS\Filesystem\File::read()</code>
<br />

To Reproduce
This cannot currently be installed in a (new) Joomla 4.1.3 or 4.1.4. An error message appears in each case...

**Additional context**

Damage during the download can be ruled out. File has been downloaded multiple times and attempted to install.

In addition, the defectively installed package can no longer be uninstalled via the backend afterwards, but must be removed from the database manually. The problem does not seem to occur when updating an existing JCE (based on Joomla 4.1.4 / JCE 2.9.22).

Thanks @ryandemmer for checking & advise if more infos are needed.

**Comment by ryandemmer** [comment]
Fixed in commit - https://github.com/widgetfactory/jce/commit/1b8f5d9014901275aa0367e09fdd666c4b426d30

**Comment by ryandemmer** [comment]
As a temporary workaround, install JCE Pro 2.9.22 and then update using the Joomla Updater.

**Comment by ChristineWk** [comment]
Thank you @ryandemmer for your infos x Code fix.
Will keep it open for a while for other users before closing.
