### ISSUE TITLE
xtd-button readmore breaks page layout

### ISSUE THREAD

**Issue by Chrissi2812** [widgetfactory/jce#113]
**Describe the bug**
Using the `xtd-button` for Readmore JCE has Problems creating the correct markup for Joomla to get the intro- & fulltext.

I have tried to fix the bug in Joomla (https://github.com/joomla/joomla-cms/pull/31087) but sems like the fix will never get implemented there.

**To Reproduce**
First it will put the readmore inside a wrapping `<p>` tag and when switching between Code and Editor View it will "fix" the error by closing the tags with a `&nbsp` inside that would add extra whitespace later.
Both will result in the output to be what the user wanted. We noticed it just because a customer of us has broken his page multiple times because of this.

**Expected behavior**
The Readmore insert should close the other tags. 

**Screenshots**

|Description|Image|
|----|----|
| After pressing the `xtd-button` | ![image](https://user-images.githubusercontent.com/6141652/95987240-6ec74a80-0e27-11eb-87bc-bd4c61322bea.png) |
| After swithcing between Code & Editor | ![image](https://user-images.githubusercontent.com/6141652/95987525-da111c80-0e27-11eb-8b52-2f33522a5947.png) |

https://user-images.githubusercontent.com/6141652/161576958-07ec0013-dd5c-4e14-89ec-882c0649796a.mp4

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - Version:  JCE 2.9.10

**Additional context**
This seems only to happen if the `xtd-button` is used.

**Comment by ryandemmer** [comment]
JCE has its own Readmore button in the editor toolbar, which fixes this issue.
