### ISSUE TITLE
XTD buttons not working in Joomla 4x on Custom field type Editor

### ISSUE THREAD

**Issue by umiha** [widgetfactory/jce#115]
**Describe the bug**
When using Joomla Custom field type Editor with JCE editor, then Joomla editor-xtd buttons are not working. When I click on any of buttons (except Read More) they are not working. For example if I click **Media** the screen gets grey transparent overlay but modal window doesn't show up.
Additional information - on main tab **Content** those xtd buttons works. They only not working on Joomla Custom fields.

**To Reproduce**
1. Joomla 4x and JCE editor core
2. Create Joomla Custom field (type Editor), and assign it to All categories
3. Open some new or existing Article, then go to tab "Fields"
4. Find previously created custom field, and click on Joomla editor-xtd buttons bellow JCE editor
5. You will see that modal windows is not opening, and you can not do anything with those buttons

**Expected behavior**
When clicking on Joomla editor-xtd buttons then modal window popup should show up so you can choose for example to insert Article (link), Media (image), Menu (link), etc.

**Screenshots**
![custom-field-editor-xtd-btn-not-working](https://user-images.githubusercontent.com/17588419/203299247-528e864c-680e-40c7-b1d7-17418185c34d.png)

**Desktop:**
 - OS: macOS Monterey
 - Browser: Chrome ver. 107, but same in Firefox and Safari

**CMS**
- Joomla 4.2.5
- JCE editor core 2.9.32

**Comment by ryandemmer** [comment]
This is a Joomla bug as the issue can be reproduced when the editor is set to **Editor - None** or **Editor - Codemirror**.

**Comment by umiha** [comment]
ok, thanks a lot. Will transfer this bug report to the Joomla Issue Tracker
