### ISSUE TITLE
File Browser not automatically loading after version 2.9.4 

### ISSUE THREAD

**Issue by xxniranxx** [widgetfactory/jce#118]
**Describe the bug**
In version 2.94 and lower the file browser would automatically navigate to the folder are in upon clicking upload. 
However once we upgraded to version 2.9.36 this no longer happens and the file browser simple opens up in the root directory. 
The way it was working is that JCE would get the path from the cookie 

 $inputCookie->set($name = 'wf_browser_dir', $value = 'cospas_sarsat/pdf_uploads/'.$this->item->id, $expire = 0);
 Although the cookie still loads up in the browser, it seems that JCE 2.9.36  does nothing with that and simply opens up without navigating to the given path. 

**Expected behavior**
When clicking " Upload"  the File manager should open up and navigate automatically to the folder we are in using the path from the cookie. 

**Screenshots**
Expected result 
![image](https://github.com/widgetfactory/jce/assets/119571889/0ebee307-6fa1-4855-9abe-4576f454e1fd)

The result after updated JCE 2.9.36
![image](https://github.com/widgetfactory/jce/assets/119571889/b08b1ad5-cdf9-4790-95e1-8a79ba276a18)

How might I go about fixing this issue, I'm not getting any errors in the console log.

**Comment by ryandemmer** [comment]
Fixed in commit - https://github.com/widgetfactory/jce/commit/b0b1f473d25ef831d38745a5252f135e4385c1fa

Fix will be included in the next update.

**Comment by uzielweb** [comment]
The same occurs to me, but when using in any custom component.
Example:
` <field addfieldpath="/plugins/fields/mediajce/fields" name="download" type="mediajce" label="COM_NORMAS_FORM_LBL_DOWNLOAD" description="COM_NORMAS_FORM_DESC_DOWNLOAD" hint="COM_NORMAS_FORM_LBL_DOWNLOAD" mediatype="files" directory="images/normasronca2020" />`

Does not appears file browser, instead appears like a "selected image to change it" and is impossible to insert when clicking in the  *Insert* button
