### ISSUE TITLE
I can´t see the code tab toolbar

### ISSUE THREAD

**Issue by Bocatatun** [widgetfactory/jce#12]
I have that issue after I updated to 2.6.1. Now I have installed 2.6.5 and still the same. Thanks

![error1](https://cloud.githubusercontent.com/assets/24826697/21544632/260ccbfc-cdd1-11e6-9dfe-f6e118d35726.jpg)
![error2](https://cloud.githubusercontent.com/assets/24826697/21544633/2610a3a8-cdd1-11e6-8468-047fca4a8c62.jpg)

**Comment by ryandemmer** [comment]
The Source Code Editor is only available in JCE Pro - https://www.joomlacontenteditor.net/subscribe

**Comment by Bocatatun** [comment]
:_(
