### ISSUE TITLE
editor.css in Joomla 5 is not working anymore

### ISSUE THREAD

**Issue by uzielweb** [widgetfactory/jce#122]
**Describe the bug**
editor.css in Joomla 5 is not working anymore

**To Reproduce**
install in Joomla 5, create an article, so try to access styles selector, when you have editor.css defined or any other custom css stylesheet configured in JCE

**Expected behavior**
List alll classes

**Screenshots**

**Desktop (please complete the following information):**
PHP 8.2, Maria DB 10, Joomla 5, JCE 2.9.52

**Comment by ryandemmer** [comment]
Unable to reproduce.

Note that css files for templates in Joomla 4 and 5 are typically located in media/templates/site/, not in the templates folder as in Joomla 3.

**Comment by uzielweb** [comment]
This was the case. The editor.css was in the correct /media folder... I will test in new versions later.
