### ISSUE TITLE
JCE version 2.9.54 & 2.9.53 do not save in Joomla 3.10

### ISSUE THREAD

**Issue by peterhulst** [widgetfactory/jce#123]
**Describe the bug**
JCE (Core) version 2.9.54 & 2.9.53 do not save in Joomla 3. With version 2.9.51 there is no problem with saving the article

**To Reproduce**
1. Go to any article in the backend (frontend: not tested)
2. Modify and save
3. The article is NOT changed.

**Expected behavior**
After SAVE the modified article should be visible

**Screenshots**
---

**Desktop (please complete the following information):**
 - OS: W11
 - Browser Edge
 - Version (any)

**Additional context**
Joomla 3.10

**Comment by ryandemmer** [comment]
Unable to reproduce in JCE Core 2.9.54

**Comment by peterhulst** [comment]
Both on an online (PHP 8.0) and a local installation (PHP 7.4) version 2.9.54 and 2.9.53 do NOT save the changes. 
_But version 2.9.51 saves without any problems._

**Comment by peterhulst** [comment]
Hello, 
I discovered the reason of this issue.
I have an editor switcher installed (e.g.L https://github.com/Bakual/editors_switcher/)
When I disable this plugin, version 2.9.51 - 2.9.55 works as expected.

Regards,
Peter
