### ISSUE TITLE
Joomla 3 and Virtuemart latest version cannot load editor - ERROR in editor.min.js

### ISSUE THREAD

**Issue by raramuridesign** [widgetfactory/jce#125]
@ryandemmer Details of a bug detected on J3. 

**Describe the bug**
Editor will not load when creating or editing new products. Works fine in K2 and normal content.
JCE is the latest version. 

Uncaught ReferenceError: Joomla is not defined
    at editor.min.js?cba01d32b7b61f25ef821d6bfaf0027a:474:30
    at editor.min.js?cba01d32b7b61f25ef821d6bfaf0027a:479:2

![image](https://github.com/widgetfactory/jce/assets/902376/df69ca4b-95c7-4a78-97c0-06ed2bf7987c)
![image](https://github.com/widgetfactory/jce/assets/902376/372bfe1a-5b17-4ef6-b005-fff1e2cb7b83)

**Expected behavior**
Editor should load

**Desktop (please complete the following information):**
n/a

**Comment by ryandemmer** [comment]
Fixed in commit - https://github.com/widgetfactory/jce/commit/084b473e87e0bfa390c2e9c8c869288c40b004b6

**Comment by raramuridesign** [comment]
@ryandemmer Thank you, when do you expect to release a new version ?
M.

**Comment by ryandemmer** [comment]
JCE Pro 2.9.76 will be released next week. You can test the dev version by downloading it here - https://www.joomlacontenteditor.net/downloads/editor/pro/development

**Comment by raramuridesign** [comment]
Thanks @ryandemmer - I am closing.
