### ISSUE TITLE
JCE File Browser not loading for Intro Image, Full Text Image

### ISSUE THREAD

**Issue by JackJoeJack** [widgetfactory/jce#126]
**Describe the bug**
Since JCE version 2.9.6.3, when selecting images at the "images and links" tab (either back-end or front-end), the file browser is not the one from JCE.

**To Reproduce**
1. Adding/editing an article, click at the "images and links" tab
2. Click on the "Select" button of the intro image (or the full article image)
3. The file browser is not the one from JCE!

**Expected behavior**
As with version 2.9.6.3, I expect to use JCE's file browser, which is much superior to the default Joomla's browser.

**Desktop**
 - OS: MacOS 12, or Ubuntu 22, or Windows 11
 - Browser: Google Chrome, Edge, Safari
 - Version: Joomla 4.4.6 or 5.1.2, JCE 2.9.7.9 (since version 2.9.6.3 which still works as expected!)

**Additional context**
I've tried several solutions, like placing the JCE system extension at the top, at the start, and also following these links:
[Link 1](https://www.joomlacontenteditor.net/support/faq/editor/revert-to-using-the-joomla-media-manager-in-intro-image-etc-2)
[Link 2](https://www.joomlacontenteditor.net/support/faq/editor/jce-file-browser-not-loading-for-intro-image-full-text-image-etc-2)

Also I noticed that with JCE version 2.9.7.9, the option to select JCE File Browser for image fields (that was at the parameters) is now missing!

**Comment by ryandemmer** [comment]
Conversion of the Joomla Media Field to use the JCE File Browser is now only available in [JCE Pro](https://www.joomlacontenteditor.net/buy)
