### ISSUE TITLE
Move button not alway working directly

### ISSUE THREAD

**Issue by buro26-tom** [widgetfactory/jce#128]
**Describe the bug**
After seeing this _Fixed the inability to re-order editors in a Subform field._ in the recent changelog, I tested the reordering of items in the subform. When clicking and dragging with the move button it will not always work directly. I found that I had to click multiple times before I can drag and drop.

**To Reproduce**
1. Go to subform
2. Click on move icon
3. Drag to change order

**Expected behavior**
After clicking and dragging the items the should change the order.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome, Firefox
 - Version Newest (auto update)

**Additional context**
Strange thing is, sometimes it works directly, not per definition after an refresh or something, can't figure out when it works like it should or why sometimes it doesn't.

If helpful I can provide a GIF screen video

**Comment by ryandemmer** [comment]
The actual move button is not part of JCE, but a feature of the Joomla subform. Any issues with these buttons adn their behaviour should be reported as a Joomla issue - https://github.com/joomla/joomla-cms/issues

**Comment by buro26-tom** [comment]
> The actual move button is not part of JCE, but a feature of the Joomla subform. Any issues with these buttons adn their behaviour should be reported as a Joomla issue - https://github.com/joomla/joomla-cms/issues

Ah my sincere apologies, I did not know this. Thanks for letting me know and pointing me in the right direction.

**Comment by ryandemmer** [comment]
It works Ok, it's just not the smoothesst drag & drop. 

![](https://cdn.joomlacontenteditor.net/tmp/subform-reorder.gif)

Re-ordering with arrows (up / down) might be better.
