### ISSUE TITLE
JCE Media Field multiple erros when in subform

### ISSUE THREAD

**Issue by JackJoeJack** [widgetfactory/jce#130]
**Describe the bug**
I have two cases of JCE Media fields that are present in subforms where I can see the following errors:
1. When I click the "select" button, and select the file, and then press the "insert", it does nothing (not to mention that the modal also has Joomla's buttons at the bottom right)
2. Another case where I already had content (probably due to a time when it worked in a previous JCE version), the modal is ok, but the insert does nothing).

**To Reproduce**
1. create a custom field of type JCE Media
2. create a sub-form and add that field
3. go to an article that has that sub-form, and add a row
4. try to add content

**Expected behavior**
It is supposed to place the selected file name/path into the input

**Screenshots**
- Add field:
![image](https://github.com/user-attachments/assets/a3ea82f8-d0c1-453d-8c12-38470f679978)
- Add sub-form:
![image](https://github.com/user-attachments/assets/92d29ab3-9898-4a91-a112-5f84ec6af4ac)
- Article add row:
![image](https://github.com/user-attachments/assets/5403cbba-86ca-47b4-b46d-c6103ff80b27)
- Modal:
![image](https://github.com/user-attachments/assets/43797722-6268-433b-a73f-c734fd3b8425)
- Error in the console:
![image](https://github.com/user-attachments/assets/60e6f0ad-7b73-441d-b936-e68009b4535a)
- Modal with double buttons!
![image](https://github.com/user-attachments/assets/a405383d-b2eb-4a89-ad23-701dca0a53ac)

**Desktop (please complete the following information):**
 - OS: MacOS 12
 - Browser: Chrome
 - Version: 128.0.6613.114

**Additional context**
- JCE Core 2.9.80
- Joomla 5.1.4 or Joomla 4.4.8

**Errors**
- I noticed that there is a JS error when adding a row: "media.min.js?e4af04:73 Uncaught TypeError: row.find is not a function" → (media.min.js?e4af04:73:138)

**Comment by ryandemmer** [comment]
Fixed in commit - https://github.com/widgetfactory/jce/commit/33b42849ce989b5f0527ebb887f40938a79133a9

Thank you.

**Comment by JackJoeJack** [comment]
Thank you. I can confirm that this fixed both issues.
