### ISSUE TITLE
[SOLVED] JCE - VirtueMart problem switching language 

### ISSUE THREAD

**Issue by CEWebDesign** [widgetfactory/jce#15]
Hello, 

there is an issue with JCE Editor 2.6.x and VirtueMart 3.0.18 when switching language on product describtion:

[http://forum.virtuemart.net/index.php?topic=136471.msg476861#msg476861](url)
[http://forum.virtuemart.net/index.php?topic=136121.msg475022#msg475022](url)
[http://forum.virtuemart.net/index.php?topic=136274.msg475763#msg475763](url)

Please help, best regards,
Chris

**Comment by ryandemmer** [comment]
This has been addressed in JCE 2.6.9

**Comment by CEWebDesign** [comment]
It works, thank you so much!

And thanks for rel="noopener noreferrer" for target='_blank',
was not aware of the vulnerability
