### ISSUE TITLE
Possible wrong localization key in spellchecker.xml

### ISSUE THREAD

**Issue by nvyush** [widgetfactory/jce#17]
\components\com_jce\editor\tiny_mce\plugins\spellchecker\spellchecker.xml

For param name="engine"
```description="WF_SPELLCHECKER_PARAM_GOOGLESPELL_LANGUAGES_DESC"```
must be replaced with
```description="WF_SPELLCHECKER_PARAM_ENGINE_DESC"```

**Comment by ryandemmer** [comment]
Fixed in commit - https://github.com/widgetfactory/jce/commit/821111377a1204b3738409b7171889d5a3dea275
