### ISSUE TITLE
Untranslatable options in article.xml

### ISSUE THREAD

**Issue by nvyush** [widgetfactory/jce#18]
\components\com_jce\editor\tiny_mce\plugins\article\article.xml

Please, make the options 'Readmore' and 'Pagebreak' translatable and add needed keys to the file ```\administrator\language\en-GB\en-GB.com_jce.ini```

**Comment by ryandemmer** [comment]
Fixed in commit - https://github.com/widgetfactory/jce/commit/23b089f2c3cb5edc1217305c9f9ba43be2c30b36
