### ISSUE TITLE
Dialog 'Create E-mail Address' has some issues

### ISSUE THREAD

**Issue by nvyush** [widgetfactory/jce#20]
The dialog 'Create E-mail Address' of the dialog 'Link' has some issues:

1) The label for address field 'To' is displayed as 'mailto' and is not translatable. I suggest to rename the key 'WF_LINK_DLG_TO' to 'WF_LINK_DLG_MAILTO' in the file ```/language/en-GB/en-GB.com_jce.ini```.

2) The caption of the 'Create' button is not translatable. I suggest to add the key WF_DLG_CREATE="Create" to the file ```/language/en-GB/en-GB.com_jce.ini``` (https://github.com/widgetfactory/jce-language-site/issues/2).

3) The button 'Cancel' does not work. I suppose, it doesn't have an appropriate handler.

4) The labels of the invalid e-mail addresses in the "Alert" dialog are not translatable. I suggest modify the string [536]
```Wf.Modal.alert(s + ed.getLang('link_dlg.invalid_email', ' is not a valid e-mail address!'));```
as
```Wf.Modal.alert(ed.getLang('link_dlg.' + s, s) + ed.getLang('link_dlg.invalid_email', ' is not a valid e-mail address!'));```
in the file ```/components/com_jce/editor/tiny_mce/plugins/link/js/link.js``` (https://github.com/widgetfactory/jce/blob/master/components/com_jce/editor/tiny_mce/plugins/link/js/link.js).

**Comment by ryandemmer** [comment]
Fixed in commits:

https://github.com/widgetfactory/jce/commit/2c2c03732c392dceb8fd2114e59c5241cc45d5cb
https://github.com/widgetfactory/jce/commit/dbd0f68d04e8a8a6cb5083f879c29bfecc9237dd
https://github.com/widgetfactory/jce/commit/1c72753f6432425bfcdbc38337eb098e85b37ef0
