### ISSUE TITLE
CSS Editor: Add to selector of white-space attribute missing values 'pre-wrap', 'pre-line'

### ISSUE THREAD

**Issue by nvyush** [widgetfactory/jce#22]
Dialog "Styles" (toolbar button "Edit CSS Style"): 
The selector of white-space attribute (tab "Block", item "Whitespace") does not contain values 'pre-wrap' and 'pre-line'.

**Comment by ryandemmer** [comment]
Fixed in commit - https://github.com/widgetfactory/jce/commit/5db1213d8ac4461084741b7b2b535735c395fa85
