### ISSUE TITLE
CSS Editor: checkbox "Insert span at selection" doesn't work as expected

### ISSUE THREAD

**Issue by nvyush** [widgetfactory/jce#23]
Dialog "Styles" (toolbar button "Edit CSS Style"):
When the checkbox "Insert span at selection" is checked, the style is applied both to the inserted span that wraps the selected text and to the paragraph that contains it. I suppose the style must be applied to the inserted span only.

**Comment by ryandemmer** [comment]
Fixed in commit - https://github.com/widgetfactory/jce/commit/93c4118a05168eac81a67955a3278a16043ad0ef
