### ISSUE TITLE
Cannot select images in 2.6.11 on Google Chrome

### ISSUE THREAD

**Issue by APD183** [widgetfactory/jce#25]
Joomla version 3.6.5, JCE Core 2.6.11, tested in Google Chrome. Reproduced on our own site and on the demo JCE site. Browser caches were cleared prior to testing.

An image cannot be selected in the editor. When you click on an image, nothing happens and the following error is generated in the browser console:

> Uncaught DOMException: Failed to execute 'setBaseAndExtent' on 'Selection': There is no child at offset 1.

**Comment by ryandemmer** [comment]
This will be fixed in JCE 2.6.12

You can test the RC here - https://www.joomlacontenteditor.net/downloads/editor/item/jce-pro-2612-dev

**Comment by ryandemmer** [comment]
Fixed in JCE 2.6.12
