### ISSUE TITLE
Pressing enter after line removes cursor from editor

### ISSUE THREAD

**Issue by raviax** [widgetfactory/jce#26]
When I paste content into the editor, and press Enter to insert new paragraphs at the end of a line, the cursor disappears from the editor, and you are unable to delete. Example: I paste 2 paragraphs. There is a line break between them, not a paragraph. I press Enter after the first paragraph. Now there is a line break and a paragraph. I press Delete, but nothing happens. You have to click back into the editor on that line in order to delete the extra line break. Yes, you can type text, but you cannot Delete until you click or type other characters.

Joomla 3.7.2, JCE 2.6.12 Pro, Firefox 53.0.3 (32-bit)

**Comment by ryandemmer** [comment]
I can't reproduce this in the current version.
