### ISSUE TITLE
JCE editor (2.6.15 and 2.6.14) fails to load at frontend with Simple Email Form plugin

### ISSUE THREAD

**Issue by geriguy43** [widgetfactory/jce#27]
With the newest (updated) version of JCE editor, the textbox of Simple Email Form are fails to load. 

You can check. Here the textbox renders good:
http://bestmachinery.hu/foldmunkagepek
(JCE editor 2.6.12)

Here it isn't:
http://bestmachinery.sk/stroje-na-zemne-prace
(JCE editor 2.6.15)

Plugin's github page:
https://github.com/andrewscaya/mod_simpleemailform/tree/stable

**Comment by ryandemmer** [comment]
I have tested this and it works if you set the **Form Type** to _JForm_.

![mod_simpleemailform](https://cloud.githubusercontent.com/assets/152333/26820575/32eb022a-4a9b-11e7-9829-432c774222df.jpg)
