### ISSUE TITLE
Fatal error: Class 'WFUtility' not found in administrator/components/com_jce/models/editor.php on line 707

### ISSUE THREAD

**Issue by mwoelk** [widgetfactory/jce#29]
After updating to version 2.6.17 the editor won't load anywhere and breaks the whole site with the message: Class 'WFUtility' not found in administrator/components/com_jce/models/editor.php on line 707.

I already tried re-installing the whole JCE-Package but without success.

**Comment by ryandemmer** [comment]
Fixed in commit - https://github.com/widgetfactory/jce/commit/780644770f0358ff3d9b88fe2f0192ecd5c65daa
