### ISSUE TITLE
Custom Style with integer value breaks redisplay of JCE Editor tab

### ISSUE THREAD

**Issue by mfjames** [widgetfactory/jce#30]
This issue first appeared in JCE 2.6.9, and is still present as of 2.6.19.

Starting condition: In the Plugin Parameters page of a JCE user profile, create a custom entry in the "Select Style" list having an integer value for one of the parameters its the "Styles" field. For example: "text-indent: 0".
![image](https://user-images.githubusercontent.com/31183228/29495357-bcf40fe8-85b5-11e7-97b0-fc7f6d5d3659.png)
Symptom: Any action that tries to re-display the "Editor" tab hangs trying to show the toolbar:
- Switch to the "Code" view then attempt to switch back
- Insert an image
- Insert a link

Problem: Compare the generated page source when using "text-indent: 0" and when using "text-indent: 0em":
{"title":"No spacing","styles":{"text-indent":0,"margin-bottom":"0em"},"selector":...
{"title":"No spacing","styles":{"text-indent":"0em","margin-bottom":"0em"},"selector":..
In the first case, with the integer value, the quotes are missing. I'll leave it to the developers to work out just _why_ this breaks the page.

**Comment by ryandemmer** [comment]
Fixed in commit - https://github.com/widgetfactory/jce/commit/d8445f4562b19236bf63af76a996b54f3d4fe90b
