### ISSUE TITLE
Can't upload files named "0"

### ISSUE THREAD

**Issue by GlassGruber** [widgetfactory/jce#33]
Hey there! Small issue, tried to upload a jpg file `0.jpg`, but I got this error message:
```
Upload Failed: The file name contains an invalid extension.
```

Tried then to upload with different name and rename it with JCE and got this:

```
Error 403: INVALID FILE NAME
````

**Comment by ryandemmer** [comment]
Fixed in commit https://github.com/widgetfactory/jce/commit/64d7ab908bb1a42a68ee93b9cf782ca7a2fb4ed5
