### ISSUE TITLE
JCE color picker pop-up not working

### ISSUE THREAD

**Issue by melroy89** [widgetfactory/jce#35]
When clicking on the text color or highlighting JCE buttons.

**Expect**
I would expect a pop-up window to select the intended color.

**Actual**
Well, nothing happens at all...

**Screenshot**
<img width="1082" alt="schermafbeelding 2018-09-03 om 19 40 07" src="https://user-images.githubusercontent.com/628926/44997856-a6f5d100-afb1-11e8-9e25-b1d831e85850.png">

**Additional info**
Browser: Firefox v61
JCE: v2.6.32.
Joomla Core: v3.8.12.

**Comment by ryandemmer** [comment]
A drop-down list of colours, and a colour picker dialog is available for the text colour and background colour buttons.

![Text Colour Picker](https://cdn.joomlacontenteditor.net/tmp/text-colour-picker.gif)

**Comment by melroy89** [comment]
@ryandemmer I don't see any button for this drop down list!?!

Please, look closely in my case there is only this 'apply' button. But not this drop down arrow button :(
Reopen.

**Comment by ryandemmer** [comment]
Is the drop-down visible for you here? - https://demo.joomlacontenteditor.net

**Comment by melroy89** [comment]
Yes that site works, however this is the pro version.. I don't think that should matter, right?

So you think something is wrong with our jce version?

**Comment by melroy89** [comment]
Ps. For example the bullet drop down menu does work. But not the text /background color selection drop down. 

![screenshot_20180905-154034](https://user-images.githubusercontent.com/628926/45097262-b2b4d500-b122-11e8-8271-117c023e6220.jpeg)
