### ISSUE TITLE
Pressing Delete-key inserts span tag

### ISSUE THREAD

**Issue by kurtroesand** [widgetfactory/jce#37]
I've recently noticed a strange behavior inside of JCE.

When I want to remove an empty paragraph with the 'Delete'-key, and there is a paragraph with content below the empty paragraph, JCE inserts a span tag with some settings applied. (see screenshot)

I'm on the latest version of JCE and I'm able to reproduce this behavior on all my sites (60+)
 sites) that have the latest version of JCE.

![1234uthgfrdew](https://user-images.githubusercontent.com/205927/52637016-5bcfda80-2ece-11e9-8a4f-169675a959b8.png)

**Comment by ryandemmer** [comment]
Which browser are you using?

Please post a screenshot of the Editor Global Configuration.

**Comment by kurtroesand** [comment]
![23trk](https://user-images.githubusercontent.com/205927/52659251-2ee6ec00-2efd-11e9-8fce-5b5052dfbd1b.png)

![234w5rtyjhgf](https://user-images.githubusercontent.com/205927/52659299-4625d980-2efd-11e9-8386-5963d89a155d.png)

![24tyjtg](https://user-images.githubusercontent.com/205927/52659276-3b6b4480-2efd-11e9-85cc-5adaab5816ac.png)

**Comment by mompemompe** [comment]
I'm having the exactly same issue. 

I think it's a own setting problem, from the JCE administrator settings. But I'm not sure

**Comment by ryandemmer** [comment]
Can you reproduce this on the demo site? - https://demo.joomlacontenteditor.net/

**Comment by kurtroesand** [comment]
Ryan

I am unable to reproduce this behavior on the demo site.
