### ISSUE TITLE
2.7.5: Can't edit Profiles > Plugin Parameters > Custom Styles

### ISSUE THREAD

**Issue by ute-sch** [widgetfactory/jce#39]
JCE Editor 2.7.3 / 2.7.4 / 2.7.5 (Joomla 3.9.4)

Profiles(Default) > Plugin Parameters > Custom Styles:
I can't edit my in Version 2.7.2 or previous created custom styles and I can't edit new custom styles.
The 3-dots-menu of each style block doesn't work - I guess, it should.
![beispiel](https://user-images.githubusercontent.com/48823507/54812255-fa4c1a00-4c8a-11e9-98c6-b12319c8e304.jpg)

Sorry, I'm just a user. The JCE Forum is for subscribers only. It's not possible just to report an issue.

**Comment by ryandemmer** [comment]
This is fixed in JCE 2.7.6 - https://github.com/widgetfactory/jce/releases/tag/2.7.6

**Comment by ute-sch** [comment]
Thank you!
