### ISSUE TITLE
Load module by name instead of id

### ISSUE THREAD

**Issue by prafullwizorbit** [widgetfactory/jce#40]
Hii,
      I wants to load module by name like {loadmodule mod_custom, module_name}  instead of id like {loadmoduleid 96}. can you please suggest where i will get these setting in JCE Editor so that JCE editor can load module by its name.

Thanks

**Comment by ryandemmer** [comment]
JCE Editor does not include a facility to load modules.

The "Module" button at the bottom of the editor, for selecting and loading a module using shortcode, is a Joomla button, and does not include an option to load a module as you require.
