### ISSUE TITLE
Entity Encoding don't work with Titles

### ISSUE THREAD

**Issue by forofo** [widgetfactory/jce#42]
enable  Editor Global Configuration -> Entity Encoding: "Named" ,  and this option only works for the text although no for the titles of articles.

Please fix this issue.  Special characters of some languages are not fixed in the title of articles when are published.  Presently, we are forced to insert HTML entities in the title field (ie: ` &eacute; `->  é) to replace these  special characters (accents, etc) and avoid the ascii wrong. 

thank you for your work!

**Comment by ryandemmer** [comment]
Article titles are not processed by JCE, so this would be a Joomla issue - https://github.com/joomla/joomla-cms/issues
