### ISSUE TITLE
Error finding JCE update

### ISSUE THREAD

**Issue by twister65** [widgetfactory/jce#43]
The `<description></description>` field is missing in:
https://cdn.joomlacontenteditor.net/updates/xml/editor/pkg_jce.xml
Please, add it, it can't be null in the joomla `#__updates` table.
![description_missing](https://user-images.githubusercontent.com/26852967/57371541-4861a200-7193-11e9-8128-505e3f45bc97.png)
This issue is related to the commit:
https://github.com/widgetfactory/jce/commit/27b9fcd77491f97e107d2b31ece592c3bad6ae2f

**Comment by ryandemmer** [comment]
This is new, and perhaps unique to your system, as the JCE update manifests have never contained the <description> field, and no one has ever reported this error.

Just for the record, what Joomla version are you using, and what database type?

**Comment by twister65** [comment]
=============
System Information
=============
php: Linux pc-salon 4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019 x86_64
dbserver: postgresql
dbversion: 9.5.6
dbcollation: C
dbconnectioncollation: UTF8
phpversion: 7.2.17-0ubuntu0.18.04.1
server: Apache/2.4.29 (Ubuntu)
sapi_name: apache2handler
version: Joomla! 3.9.6 Stable [ Amani ] 7-May-2019 15:00 GMT
platform: Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
useragent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/73.0.3683.86 Chrome/73.0.3683.86 Safari/537.36

The previous manifest was:
https://cdn.joomlacontenteditor.net/updates/xml/pkg_jce.xml
And the new one is:
https://cdn.joomlacontenteditor.net/updates/xml/editor/pkg_jce.xml

PostgreSQL users are rare.

**Comment by twister65** [comment]
It is easier to add a description field in the manifest, than changes the table structure of the joomla database. With MySQL, this column is also not null. See the `#__updates` table in your database.

**Comment by ryandemmer** [comment]
The manifest files have been updated and a <description> tag added.

My point is, the <description> tag has not been in previous manifest files, and the omission has not caused a problem before.

Perhaps this is due to a change in Joomla 3.9.6

**Comment by twister65** [comment]
Thanks.
