### ISSUE TITLE
JCE Mediabox (2.0.10) issue with percentage image width.

### ISSUE THREAD

**Issue by guenkueh** [widgetfactory/jce#46]
If you choose a percentage image width and want to show the magnifying glass, then there is no textual flow; the text is displayed below.
Example:
Image width 40%; proportional
Alignment: left
Popup icon: yes

The text flow is correct when the pop-up icon is off:
Popup icon: no

**Comment by ryandemmer** [comment]
This should be posted here - https://github.com/widgetfactory/jce-mediabox
