### ISSUE TITLE
Image manager help article bug

### ISSUE THREAD

**Issue by ghost** [widgetfactory/jce#48]
It is not posible to set up our help article
Image manager help article bug then we try to open this help article in red
![Untitled](https://user-images.githubusercontent.com/43875462/59104482-5e9d8200-893a-11e9-934e-044f5ff76a25.png)

thanks for help

**Comment by ghost** [comment]
this bug not solved in jce 2.7.14

maybe you know how to hide this help button, if it is not posible to set up our help article ?

**Comment by ryandemmer** [comment]
> It is not posible to set up our help article

This is not a bug, or if it is, you have not provided any explanation as to why you think it is, or what exactly you have done in your attempt to set up the help article.

Please provide more information when submitting bug reports.

**Comment by ghost** [comment]
Ryan thank you for your comment. 

Then I click on help (provided picture above circle in red) I get this - **The requested page can't be found.**

Maybe you know how to fix this?

I tryed to find where to set up or link to my article in native language but I couldn't. Maybe I missed someting. English is not my native language, so it is not easy to explain. Big apologation if I offended you.

What information I need to provide for this bug/ or not bug report ?

**Comment by ryandemmer** [comment]
Have you set a custom Help URL in Options -> General Options?

**Comment by ghost** [comment]
Yes I set a custom Help URL in Options -> General Options, but still get this - The requested page can't be found page.

**Comment by ryandemmer** [comment]
It is not enough to just define a custom url, each article must be written and defined using the Key Reference system in the Joomla Article Manager.

You can read more about the help system here - https://github.com/widgetfactory/jce-docs

In JCE 2.8.0, options will be available for defining the help url, and offer an alternative URL based method for locating help files.

**Comment by ghost** [comment]
Ryan thank you for your help. But I still dont understand what keyword should be added as a Key Reference ? I still get this - The requested page can't be found.
