### ISSUE TITLE
Feature request: automaticaly resize image in JCE core Editor

### ISSUE THREAD

**Issue by ghost** [widgetfactory/jce#50]
we need to implement image resize feature in JCE Editor

for example then user uploads a 5Mb photo plugin that should automaticaly resize that photo to 200Kb or 70% smaller the file size?

how to implement this feature ?

can we have this feature in JCE core Editor ?

Our users think its a basic feature of a modern editor, and should be included in each JCE core edition.

Ryan, what opinion you have about this issue?

Do you plan to include this feature in JCE core 2.8 ?

**Comment by ghost** [comment]
Do you plan to include this feature in jce core 2.7.15 ?

**Comment by ryandemmer** [comment]
Image resizing is available in JCE Pro - https://www.joomlacontenteditor.net/purchase

**Comment by ghost** [comment]
Now we dont have money for Pro version. Maybe in the futute we'll have.

So as I understand our only option is to create our own free open source plugin to have this feature - resize joomla article image on upload?
