### ISSUE TITLE
Resizing Images on Upload Core JCE big bug

### ISSUE THREAD

**Issue by ghost** [widgetfactory/jce#51]
Imposible Automatic Resizing Images on Upload with Core JCE

Steps to reproduce the issue

Try to add 5 pictures to Core JCE article and you easily can get published fronted 1 article with 25 MB size. Core JCE claims to be A Content Editor for Joomla but cant even resize image, even GitHub can resize image. Or is 30MB + article normal thing for Core JCE?

**Comment by ryandemmer** [comment]
Image resizing is available in JCE Pro - https://www.joomlacontenteditor.net/purchase

**Comment by ghost** [comment]
Now we dont have money for Pro version. Maybe in the futute we'll have.

So as I understand our only option now is to create our own free open source plugin to have this feature - resize joomla article image on upload?
