### ISSUE TITLE
Tinymce version is 5.0.12

### ISSUE THREAD

**Issue by ghost** [widgetfactory/jce#52]
Does JCE 2.7.15 use tinymce version 3 ?

Will JCE 2.8 use tinymce v 3 or v4 or v5 ?

**Comment by ryandemmer** [comment]
JCE 2.7 and 2.8 use a forked and heavily modified version of Tinymce 3

**Comment by ghost** [comment]
do you plan to use tinymce v5 ?

**Comment by ryandemmer** [comment]
No.

**Comment by ghost** [comment]
What main diference is between official new version Tinymce 5 and your heavily modified version of Tinymce 3 ?
