### ISSUE TITLE
Jce Profile Bug of feature lack?

### ISSUE THREAD

**Issue by ghost** [widgetfactory/jce#56]
Is it profile bug or lack of functionality?

What is main diference between these profiles Front End Default   Blogger   Mobile  Markdown ?

I see nothing, I am missing something?

Can we have in Jce upload and insert image in article as simple as is in github?

**Comment by ryandemmer** [comment]
Issues in this repo are for bug reports only. For support, please use the Support Forum - https://www.joomlacontenteditor.net/support/forum/index

Please note - free support is not offered for JCE Core.

**Comment by ghost** [comment]
this is bug report unless you have documentation What is main diference between these profiles Front End Default Blogger Mobile Markdown ? strange tht you prefere not to share but rather close the issue

I thought better about you ryan but its your choice not mine

by the way thanks for jce core
