### ISSUE TITLE
JCE looses current directory

### ISSUE THREAD

**Issue by dautrich** [widgetfactory/jce#57]
1. Uploaded a photo to a subdirectory of the /images directory
2. When trying to upload another photo, I find myself in the root directory (/), not in the previous subdirectory.
Error or feature?

**Comment by ryandemmer** [comment]
This is a bug, fixed in commit - https://github.com/widgetfactory/jce/commit/68086be9b8f292f6375a1ca323981ad137ea054d

The fix will be included in the next update.
