### ISSUE TITLE
Call to undefined method WFMediaManager::onUpload() on manager.php:135

### ISSUE THREAD

**Issue by AndNovAtor** [widgetfactory/jce#64]
I don't understand the meaning of [95aa74e](https://github.com/widgetfactory/jce/commit/d95aa74e4680b177a57b67e6a863f0cf6087aa47). I updated to/downloaded JCE 2.8.3 ["core"] (it's last release version at the time of writing of this "issue"), and when I tired to upload file in file manager, uploading "fails" with the php fatal error `Call to undefined method WFMediaManager::onUpload()` on `manager.php:135` (when file, fortunately, was uploaded succesfuly), and the file manager show "`The server returned an invalid JSON response.`". When I "revoke" [95aa74e]
(https://github.com/widgetfactory/jce/commit/d95aa74e4680b177a57b67e6a863f0cf6087aa47) by commenting [browser.php#L135](https://github.com/widgetfactory/jce/blob/master/components/com_jce/editor/tiny_mce/plugins/browser/browser.php#L135) (` //parent::onUpload($file, $relative);`), then all works normally (I don't see any parent onUpload method...).
I tired on multiple web servers and with cleal Joomla installation with php 7.2/7.3 - same result.
So, I don't understand, what I'm "doing" wrong...

![jce_bug_1](https://user-images.githubusercontent.com/3628514/72701204-97a00500-3b5f-11ea-83e1-97d16aec9b10.jpg)
![jce_bug_2](https://user-images.githubusercontent.com/3628514/72701012-e00af300-3b5e-11ea-83e3-a5e7595f957c.jpg)

**Comment by ryandemmer** [comment]
Fixed in commit - https://github.com/widgetfactory/jce/commit/6b9ac611525d4e38605d22cad22c755cc95b483f
