### ISSUE TITLE
frontend JCE 2.8.4 image insert bug

### ISSUE THREAD

**Issue by ghost** [widgetfactory/jce#65]
![Untitled284](https://user-images.githubusercontent.com/43875462/72983514-1f993f80-3dea-11ea-9c5d-fadf021d37fc.png)

frontend JCE 2.8.4 RC2 image insert bug

**Comment by ryandemmer** [comment]
I am not able to reproduce this.

How have you selected the file? You need to click on the file name to select it for insertion.

**Comment by ghost** [comment]
click on the blue rectangle near file name then click insert blue button

**Comment by ryandemmer** [comment]
Clicking the blue rectangle does not select the image for insertion, it selects the image for processing, ie: delete, rename etc.

To select an image to insert, click on the name of the image. This will fill the url field and allow the image to be inserted into the article.

This is not a bug, and is the standard behaviour that JCE has used for many years. 
Please see - https://www.joomlacontenteditor.net/support/documentation/image-manager/insertupdate

**Comment by ghost** [comment]
YesI I know but this JCE 2.8.4 behavior is very confusig for new users, I get very angry comments that they cant insert picture and lots of these screenshots.

is it posible to fix this JCE 2.824 UI bug, couse now this standard behaviour is very confusig for new users?
