### ISSUE TITLE
Help URL Pattern JCE 2.8.4 RC2 page can't be found page

### ISSUE THREAD

**Issue by ghost** [widgetfactory/jce#67]
Help URL Pattern

Documentation?

Ryan please add screenshot of working real example how to configure using the syntax $1/$2/$3 ?

Still get this - the requested page can't be found page.

**Comment by ryandemmer** [comment]
Although it is not actively used, this repo - https://github.com/widgetfactory/jce-docs - is a copy of the current help file content and layout that runs on the JCE site.

You can use this repo as a source for your own help site, for content and file / folder structure.

Your help files should follow the same structure as laid out here - https://github.com/widgetfactory/jce-docs/tree/master/en

The corresponding custom help site url would then include variables that relate to the items in this structure, eg:

https://www.myhelpsite.com/docs/jce/$1/$2/$3 might then point to https://www.myhelpsite.com/docs/jce/editor/about or https://www.myhelpsite.com/docs/jce/manager/delete depending on the help topic selected by the user.

**Comment by ghost** [comment]
Ryan, so in JCE 2.8.4 RC2 you still need to upload all repo files?

We dont need help site, we just need just 1 article. 

You still cant create article in joomla and then just put this articles url as Help URL?
