### ISSUE TITLE
Disable this in JCE 2.8.4 RC3

### ISSUE THREAD

**Issue by ghost** [widgetfactory/jce#68]
**Describe the bug**
Not possible to disable this "? Help" text in red sircle. in JCE 2.8.4 RC3
![Untitled](https://user-images.githubusercontent.com/43875462/73150387-d0475d80-40ce-11ea-9af6-9a18b2c562f0.png)

**Expected behavior**
A way to disable it. Do not show this "? mark and Help text" in red sircle.

**Screenshots**
added screenshots to help explain problem, our users dont want to see this "? mark and Help" text in red sircle.

**Additional context**
Ryan, is there any way to disable it? Our users don't want to see this.
JCE 2.8.4 RC3 and Joomla 3.9.14

**Comment by ryandemmer** [comment]
There is no specific option for disabling the Help button, but this can be done with some css.

Create a plugin.css file in media/jce/css folder and add the following:
```css
#help {
    display: none;
}
```
