### ISSUE TITLE
"The server returned an invalid JSON response." when uploading file (file does still upload)

### ISSUE THREAD

**Issue by benvoth** [widgetfactory/jce#69]
When uploading a file (I'm working with a PDF) from the "JCE FIle Browser" in the back-end, the file does upload but I'm getting this error: "The server returned an invalid JSON response." Here's a screenshot: https://ibb.co/2vwr0Tm

I'm using:
JCE 2.8.3
Joomla 3.9.14
PHP 7.3 (also tested in PHP 5.6, same issue)

Can you help out?

Thanks.

**Comment by ryandemmer** [comment]
Fixed in commit - https://github.com/widgetfactory/jce/commit/6b9ac611525d4e38605d22cad22c755cc95b483f

The fix will be included in the next update.

**Comment by benvoth** [comment]
Thank you! Do you have a date scheduled for the next update?
