### ISSUE TITLE
JCE 2.8.6: files up to 10 MB in size 

### ISSUE THREAD

**Issue by ghost** [widgetfactory/jce#72]
**Describe the bug**

try to upload image in frontend you see this text " files up to 10 MB in size "

**Expected behavior**

posibility to not to show this text or change this text

**Comment by ryandemmer** [comment]
This will be fixed in the next update with the addition of a label in the language file which can be overridden

https://github.com/widgetfactory/jce/commit/56dc7f51f5f9482e640320327d4486f0e49e2ddd

**Comment by ghost** [comment]
Ryan how this  " files up to 10 MB in size " text can be overriddenor not displayed?

Still unable to do this in JCE 2.8.9 is it fixed now?
