### ISSUE TITLE
JCE 2.8.10: files up to 20 MB in size

### ISSUE THREAD

**Issue by ghost** [widgetfactory/jce#74]
Describe the bug

try to upload image in frontend you see this text " files up to 20 MB in size "

Expected behavior

posibility to not to show this text or change this text

Ryan how this " files up to 20 MB in size " text can be overridden or not displayed?

Still unable to do this in JCE 2.8.10 is it fixed now?

Where is the file with addition of a label in the language file which can be overridden?

**Comment by ryandemmer** [comment]
This is done using a language override.

Go to Extensions -> Languages -> Overrides

Set **Select Language & Client** to _English (en-GB) - Site_ or whatever language you are using.

Click the **New** button, and then in the **Language Constant** field, paste in WF_DLG_UPLOAD_DROP_DETAILS

For the **Text** field, add whatever text you want to use for the label.

Click **Save**.

![](https://cdn.joomlacontenteditor.net/tmp/jce-github-issue-74.jpg)

**Comment by ghost** [comment]
Ryan you should try to use this Language Constant field, paste in WF_DLG_UPLOAD_DROP_DETAILS in JCE 2.8.10 because it makes no effect, still the issue remains, how to fix this?

**Comment by ryandemmer** [comment]
It definately does work, and has been tested in JCE Pro 2.8.10

Please follow the instructions I set in my previous post, in particular, the client must be set to **Site**.

**Comment by ghost** [comment]
Ryan, WF_DLG_UPLOAD_DROP_DETAILS 

constant doesn't work, maybe the constant is wrong, or there is spelling mistake in it, do you use same letters as above, please copy and paste them in your demo site or check if its the same constant with the same letters???

If you try to upload image in frontend you see this text " files up to 20 MB in size "

**Comment by ryandemmer** [comment]
Please see my screenshot above. Your override should match this exactly, except for the **Text** box, which should contain your own desired text.

This has been tested and does work with the settings in the screenshot above.

**Comment by ghost** [comment]
Ryan I dont know why other overrides work but this one in particular doesnt :(
Ryan it doesnt work  with Language Constant field WF_DLG_UPLOAD_DROP_DETAILS nor with VF_DLG_UPLOAD_DROP_DETAILS as is in screenshot 

Ryan does it work for you only in JCE Pro 2.8.10 but doesnt work in JCE 2.8.10 ?
Does in work in bouth JCE Pro 2.8.10 and JCE 2.8.10 ?
It doesn't work in bouth JCE Pro 2.8.10 and JCE 2.8.10 ?
