### ISSUE TITLE
Ryan please fix this bug in JCE 2.8.11 RC2

### ISSUE THREAD

**Issue by ghost** [widgetfactory/jce#75]
Please fix Language Constant field in JCE 2.8.11 RC2

files up to "?" MB in size

in #74 Ryan you provided 2 diferent constants to fix this, why? Whick one to use?

Ryan I dont know why other overrides work but this one in particular doesnt :(
Ryan it doesnt work with Language Constant field WF_DLG_UPLOAD_DROP_DETAILS nor with VF_DLG_UPLOAD_DROP_DETAILS as is in your screenshot

Ryan does it work for you only in JCE Pro 2.8.10 but doesnt work in JCE 2.8.10 ?
Does it work in bouth JCE Pro 2.8.10 and JCE 2.8.10 ?
It doesn't work in bouth JCE Pro 2.8.10 and JCE 2.8.10 ?

Please post results we need to fix it in JCE 2.8.11

files up to "4.88" MB in size

![dis](https://user-images.githubusercontent.com/43875462/80675572-771c0b00-8abd-11ea-87a4-c5f4b4e07d88.png)

we want to see it like this

up sizes  

instead we still have this 

files up to "4.88" MB in size

**Comment by ryandemmer** [comment]
> in #74 Ryan you provided 2 diferent constants to fix this, why? Whick one to use?

I provided only one constant in my post

> Click the New button, and then in the Language Constant field, paste in WF_DLG_UPLOAD_DROP_DETAILS

This is tested and is working.

Your results will depend on what you are entering into the Text field as indicated in https://github.com/widgetfactory/jce/issues/74

**Comment by ryandemmer** [comment]
If you don't want the value to show anything, enter in a blank space.
