### ISSUE TITLE
Amazon S3 Bucket - An image inserted directly into the editor using drag & drop would not display after upload if the Filesystem==AmazonS3

### ISSUE THREAD

**Issue by smosca** [widgetfactory/jce#77]
Version used 2.8.12

An image inserted directly into the editor using drag & drop would not display after upload if the Filesystem==AmazonS3

**Comment by smosca** [comment]
Tested on Safari 13.1 and Chrome 81.0.4044.138

**Comment by ryandemmer** [comment]
Fixed in commit - https://github.com/widgetfactory/jce/commit/126924229113dbcf566d85067c83364965d5fb3a

Please note this issue will only currently occur if the file is uploaded with the ACL Level as Private, which is the default.
