### ISSUE TITLE
jce file browser in custom field (repeatable) » Form Field Type Media

### ISSUE THREAD

**Issue by pitcock** [widgetfactory/jce#80]
Hi,

using a custom field (media) shows nicely the jce file browser.
Using a custom field (repeatable) » Form Field Type Media shows the default Joomla media manager.

<img width="557" alt="cf-screen" src="https://user-images.githubusercontent.com/28976674/85998223-cf628100-ba0a-11ea-96e2-e57f699c7a61.png">

It would be a great improvement to have your ice file browser also in the Form Field Type Media.

**Comment by ryandemmer** [comment]
Supported since JCE 2.9.3
