### ISSUE TITLE
"Administrator" not able to edit profiles even with all rights set to "allow"

### ISSUE THREAD

**Issue by TLWebdesign** [widgetfactory/jce#81]
**Describe the bug**
I have a user from group "Administrator" that received full rights to JCE. 

But when i try to edit a profile i get "403 You are not authorised to view this resource. " 

It tries to search for a jce.profile rights but these don't exist. Only jce.profiles exist. So it's searching for a non-existent rights setting.

The problem lies in that there is no jce.profile rights. but you do search for one. Adding this manually in the db assets table fixed the issue so i believe it's quite clear that this is a bug.

**Where? **
/administrator/components/com_jce/controller.php:98 throws the error because on line 97 you're doing a false check.

**Expected behavior**
Able to edit profile.

**Actual behaviour**
403 forbidden error message.

**Comment by ryandemmer** [comment]
Fixed in commit - https://github.com/widgetfactory/jce/commit/b3aabb0036b2234d843ae523853aab936027105b

Thank you.
