### ISSUE TITLE
JCE 2.9.2 file bug strange files

### ISSUE THREAD

**Issue by ghost** [widgetfactory/jce#82]
JCE 2.9.2 Beta 11 file name upload bug 

To Reproduce

Try to create article in frontend and try to upload image name for example bugjce292.jpgdotnotremovejce.jpg

without any error you get uploaded file name with the dot bugjce292.jpgdotnotremovejce.jpg

**Expected behavior**

dot removed from file name and changed with -

bugjce292-jpgdotnotremovejce.jpg

joomla 3.9.22

**Comment by ryandemmer** [comment]
```
Try to create article in frontend and try to upload image name for example bugjce292.jpgdotnotremovejce.jpg
without any error you get uploaded file name with the dot bugjce292.jpgdotnotremovejce.jpg
```
This is the expected behaviour, as JCE allows dot characters in file and folder names.
