### ISSUE TITLE
Logo missing in Joomla 4.0 component dashboard

### ISSUE THREAD

**Issue by frostmakk** [widgetfactory/jce#85]
![image](https://user-images.githubusercontent.com/25645600/106820151-2607fb80-667b-11eb-95b2-f3b77dd61fc1.png)

Console error 404 .
Expected to be /administrator/components/com_jce/media/img/menu/logo.png
But the file is located in /administrator/components/com_jce/media/img/logo.png

**Comment by ryandemmer** [comment]
Fixed in commit - https://github.com/widgetfactory/jce/commit/c74696a9378d57c6f416ddd081cc823b0aa74007

Thank you
