### ISSUE TITLE
Syntax error in jce/plugins/system/jce/jce.php

### ISSUE THREAD

**Issue by stefanoel** [widgetfactory/jce#86]
**Describe the bug**
On JCE Editor Core 2.9.4 at line 29 there is a misspelled variable name:
$mediatpye = $app->input->get('view', 'images');
that generate a notice.

**Expected behavior**
$mediatype = $app->input->get('view', 'images');

**Comment by ryandemmer** [comment]
Fixed in commit https://github.com/widgetfactory/jce/commit/baffd4dc71b5d6936a7d84cafb7b75c3fcc8dbe1

Thank you!
