### ISSUE TITLE
bug in JCE 2.9.5 RC1

### ISSUE THREAD

**Issue by richarduch** [widgetfactory/jce#87]
bug in JCE 2.9.5 RC1 

missing the addition of a label in the language file which can be overridden :

Image

Url

Description

Cancel

Close

**Comment by ryandemmer** [comment]
These labels use existing keys in the language/en-GB/en-GB.com_jce.ini file.

**Comment by richarduch** [comment]
What are existing keys ? Keys are constants or something different?

ln language/en-GB/en-GB.com_jce.ini file there are no URL line, if I miss it in which line it is ?

Are also missing in this file:
Image
URL
Description
Cancel
Close
Browse

For example I try to overridde URL to URLi  but get nothing, am I doing something wrong?
