### ISSUE TITLE
bug in JCE 2.9.5

### ISSUE THREAD

**Issue by richarduch** [widgetfactory/jce#88]
addition of a label in the language file which can be overridden doesnt work: 

Url

Description

For example I try to overridde URL to URLi but get nothing, am I doing something wrong?

Description to Descripti also doesnt work

ln language/en-GB/en-GB.com_jce.ini existing keys doesnt work?

**Comment by ryandemmer** [comment]
Duplicate post, not a bug.

**Comment by richarduch** [comment]
Ryan this is same bug which still remains in JCE 2.9.5 that you not fixed in JCE 2.9.5 RC1 ?

**Comment by ryandemmer** [comment]
There is no bug.

The labels for the Basic Dialog are set in the language/en-GB/en-GB.com_jce.ini, but are not unique. The label keys that apply are:

WF_DLG_URL
WF_DLG_DESCRIPTION

These were added in 2.9.5
