### ISSUE TITLE
key bug in JCE 2.9.5

### ISSUE THREAD

**Issue by richarduch** [widgetfactory/jce#89]
key bug in JCE 2.9.5

existing 2 keys doesnt work:
Not possible to override **URL to URLi** 
Not possible to override **Description to Descripti** 
other keys work but these 2 keys still not working, seems like bad quality code
Not fixed since jce 2.9.5 RC1 remains in jce 2.9.5 

Ryan thank you in advance for trying to fix it

**Comment by ryandemmer** [comment]
![](https://cdn.joomlacontenteditor.net/tmp/github-issue-89-1.jpg)
![](https://cdn.joomlacontenteditor.net/tmp/github-issue-89-2.jpg)

It's working fine.

**Comment by richarduch** [comment]
strange maybe something with my side, I'll do reinstall
