### ISSUE TITLE
upload too small, possible to make it bigger? JCE 2.9.6 Beta 3

### ISSUE THREAD

**Issue by richarduch** [widgetfactory/jce#90]
How to let users just to upload picture and do not let users write url in that line? how to make upload insert image icon large?

Is it possible to make this red row clickable to upload image?

Is this option missing or bug?

Additional context
same bug in JCE 2.9.6 Beta 3 and JCE 2.9.5 bug

**Comment by ryandemmer** [comment]
> How to let users just to upload picture and do not let users write url in that line?

This is not configurable.

> Is it possible to make this red row clickable to upload image?

No, the URL field is an input text box. Click the upload button to select and upload an image, or drag and drap an image into the URL field.

**Comment by richarduch** [comment]
Ryan maybe you know how to make upload button more visible? Maybe to paint it in color and make it bigger?
