### ISSUE TITLE
bug in JCE 2.9.5 Classes disappeared

### ISSUE THREAD

**Issue by richarduch** [widgetfactory/jce#91]
**Describe the bug**
Image manager Use basic dialog Classes are removed, Classes works only if Use basic dialog is set to no.

**Expected behavior**
Classes works in Image manager Use basic dialog set to yes

**Additional context**
same bug in JCE 2.9.6 Beta 3 and JCE 2.9.5 bug

**Comment by ryandemmer** [comment]
Fixed in commit - https://github.com/widgetfactory/jce/commit/ae3957e6f062edc31e11c7b0a10475bb0dded48c
