### ISSUE TITLE
cache issue ?? Language texts not shown in cached mode (variable names instead)

### ISSUE THREAD

**Issue by NetSecond** [widgetfactory/jce#94]
If you use the editor while the page content is not yet in the cache, everything is displayed correctly (e.g. descriptions of the buttons).
If you close the browser and reopen it again, the variables are displayed instead of the button descriptions.
If you delete the caching of the page or deactivate the caching completely, the display works again.

Example:
Open browser,
Mouse on "B" (Bold),
"Bold (Crtl + B)" appears,
Close browser,
Restart browser,
Mouse on "B" (Bold) ",
it appears:
"advanced.bold_desc",
Clear or deactivate cache,
everything OK again.

I suspect a cache problem here.

**Comment by ryandemmer** [comment]
Not seeing this issue on the demo site in Chrome or Firefox.

**Comment by NetSecond** [comment]
Ok, maybe its a cache problem on my installations.
Other editors will work ok.
