### ISSUE TITLE
[J!4.0][JCE2.9.11] Warning: Undefined array key 1

### ISSUE THREAD

**Issue by ReLater** [widgetfactory/jce#97]
**Describe the bug**
- Haven't tested with Joomla 3. Maybe the same?
- The site is migrated from Joomla 3.
- JCE 2.9.11
- Set Joomla's `Error reporting` to "Maximum".
- Open article (new or existing one).
- I see 
`Warning: Undefined array key 1 in /components/com_jce/editor/libraries/classes/editor.php on line 269`
- https://github.com/widgetfactory/jce/blob/2.9.11/components/com_jce/editor/libraries/classes/editor.php#L269
- When I debug $userParams I get:
```
Array
(
    [0] => 
)
```
- The empty string fails in line 269.

**Comment by ryandemmer** [comment]
Do you have any values set in the Custom Configuration Variables parameter in the Editor Global Configuration?

**Comment by ReLater** [comment]
> Do you have any values set in the Custom Configuration Variables parameter in the Editor Global Configuration?

No just the 2 empty fields (the default ones).

Looks like an orphaned entry in db somwhow.
- In Joomla 3 (same site, same settings, same configurations): No warning.
- In Joomla 4 (same site, same settings, same configurations): Warning.
- - After adding a second "Custom Configuration Variables" with plus sign. removing it without saving the configuration and saving the editor configuration then the warning is gone. Magic...

Therefore I'm closing here. Thanks for your time.

**Comment by ryandemmer** [comment]
Fixed in commit - https://github.com/widgetfactory/jce/commit/e88a954f4d8f713cc96156fe3563b02af291e164
