### ISSUE TITLE
[JCE2.9.11] Protect Shortcode destroys HTML entities between 2 shortcodes

### ISSUE THREAD

**Issue by ReLater** [widgetfactory/jce#98]
**Describe the bug**
- When `Protect Shortcode` is activated HTML entities are converted to "real" HTML tags when between two shortcodes.

**To Reproduce**
- JCE 2.9.11. 
- Joomla 3.10 and 4.0.
- PHP 8
- Go to JCE > Edit Profile > Editor Parameters > Activate `Protect Shortcode`
- Open an article
- Paste this code in HTML editor

```
<div class="div4hyphens">
...
</div>
```
- After it add a shortcode like `{loadmoduleid 204}`
- After it paste HTML code above again.
- Save article: All OK. See image:
![grafik](https://user-images.githubusercontent.com/20780646/131226415-e4b168fb-9c73-422f-8797-d7edec60178c.png)
-  After it add another shortcode like `{loadmoduleid 187}`
- Save article: The HTML entities betwen the two shortcodes are converted to "real" HTML and pasted code snippet appears like follows (see image, red arrow):
![grafik](https://user-images.githubusercontent.com/20780646/131226504-0a339ee0-f66f-485d-a2a6-c7a06d601012.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Firefox
 - Version current

**Comment by ryandemmer** [comment]
Fixed in commit - https://github.com/widgetfactory/jce/commit/949ddbda60a12e41f5305008125ff1135f87cf14
